# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4aed91de75401f6de4a54526856345738a8c4f4ea30f0326ab1ac1f157345767cd10ef3fa4da11082becc1f0aca72ac4211e50b5bb397015cc40082133b65b05

test:
  secret_key_base: 63d0f58a0dc37ce780207f5c96084708aee087522aca658413047c8cc678ccf5308a02451d277fed2f2876e686f3b1e2c49207634a660234af7085c65bc98324

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
